# ============================================================
# app/models/schemas.py
#
# Pydantic v2 models used across the entire API.
# These are the "contracts" between our backend and all clients
# (mobile app, web dashboard, other microservices).
#
# Naming convention:
#   <Entity>Create  — payload for POST (creating a resource)
#   <Entity>Update  — payload for PATCH (partial update)
#   <Entity>Out     — response sent to the client
#
# This file consolidates models from the original Pacha Cover
# codebase and all four extended features:
#   Feature 1: Pacha Vision AR
#   Feature 2: Green Corridor Clustering
#   Feature 3: AI Carbon Credit & Tax Simulator
#   Feature 4: Bhasha Vernacular Voice Interface
# ============================================================

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


# ── Shared primitives ──────────────────────────────────────────────────────────

class Coordinates(BaseModel):
    """Geographic point. Latitude/longitude in WGS-84."""
    latitude: float = Field(..., ge=-90, le=90, examples=[12.9716])
    longitude: float = Field(..., ge=-180, le=180, examples=[77.5946])


class APIResponse(BaseModel):
    """Generic wrapper for successful responses."""
    success: bool = True
    message: str = "OK"
    data: Any = None


# ── Heat Map ───────────────────────────────────────────────────────────────────

class HeatRiskLevel(str, Enum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


class WardHeatData(BaseModel):
    """
    Heat and greenery snapshot for one BBMP ward.
    Populated from Google Earth Engine (NDVI + LST bands).
    """
    ward_id: str = Field(..., examples=["ward_147"])
    ward_name: str = Field(..., examples=["Koramangala"])
    # Land Surface Temperature in °C (from Landsat/MODIS LST band)
    avg_land_surface_temp: float = Field(..., description="°C")
    # Normalised Difference Vegetation Index (-1 to 1)
    avg_ndvi: float = Field(..., ge=-1, le=1)
    # Percentage of ward area classified as green cover
    green_cover_percent: float = Field(..., ge=0, le=100)
    # Composite risk score (0–100)
    heat_risk_score: float = Field(..., ge=0, le=100)
    heat_risk_level: HeatRiskLevel
    # Number of adopted spots in this ward (from Firestore)
    adopted_spots_count: int = 0
    last_updated: datetime = Field(default_factory=datetime.utcnow)
    # GeoJSON polygon of the ward boundary (optional for map rendering)
    boundary_geojson: dict | None = None


class HeatMapResponse(BaseModel):
    """Response for GET /heatmap"""
    wards: list[WardHeatData]
    data_source: str = "Google Earth Engine (Landsat 8 + MODIS)"
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    total_wards: int


# ── Prescription / Species Recommender ────────────────────────────────────────

class PrescriptionRequest(BaseModel):
    """
    Input for POST /prescribe.
    The client sends GPS coords + optional context from on-device sensors.
    """
    coordinates: Coordinates
    # Optional enrichment — mobile app can include these for better recs
    nearby_land_use: str | None = Field(
        None,
        examples=["residential", "commercial", "roadside", "park"],
    )
    soil_type: str | None = Field(None, examples=["red laterite", "clay", "sandy"])
    plot_area_sqm: float | None = Field(None, gt=0, examples=[25.0])
    ward_name: str | None = Field(None, examples=["Koramangala"])


class TreeSpecies(BaseModel):
    """A recommended tree species with Gemini-generated rationale."""
    common_name: str = Field(..., examples=["Neem"])
    scientific_name: str = Field(..., examples=["Azadirachta indica"])
    kannada_name: str | None = Field(None, examples=["ಬೇವು"])
    why_recommended: str = Field(
        ...,
        description="Plain-language explanation generated by Gemini 1.5 Pro",
    )
    # Practical planting metadata
    expected_canopy_spread_m: float | None = None
    water_requirement: str | None = Field(None, examples=["Low", "Medium", "High"])
    growth_rate: str | None = Field(None, examples=["Fast", "Moderate", "Slow"])
    co2_absorption_kg_per_year: float | None = None
    # Rotary Focus Area alignment
    rotary_focus: str = Field(
        default="Environment",
        examples=["Environment", "Community Economic Development"],
    )


class PrescriptionResponse(BaseModel):
    """Response for POST /prescribe"""
    coordinates: Coordinates
    primary_recommendation: TreeSpecies
    alternative_recommendations: list[TreeSpecies] = []
    gemini_model_used: str
    # Soil & satellite data auto-detected by SoilHealthService
    soil_analysis: dict | None = None
    disclaimer: str = (
        "Recommendations are AI-generated. Consult a local horticulturist "
        "for site-specific advice."
    )


# ── Green Ledger / Adopt-a-Spot ────────────────────────────────────────────────

class AdoptionStatus(str, Enum):
    PLEDGED = "pledged"          # User committed but hasn't planted yet
    PLANTED = "planted"          # Tree planted, awaiting first verification
    VERIFIED = "verified"        # At least one successful growth verification
    COMPLETED = "completed"      # Reached 3 verifications (full lifecycle)
    ABANDONED = "abandoned"      # Flagged inactive


class AdoptSpotCreate(BaseModel):
    """Payload for POST /ledger/adopt"""
    coordinates: Coordinates
    spot_name: str = Field(
        ..., min_length=3, max_length=100,
        examples=["Near HSR Layout Metro Station"],
    )
    ward_name: str = Field(..., examples=["Koramangala"])
    species_common_name: str = Field(..., examples=["Neem"])
    species_scientific_name: str | None = None
    notes: str | None = Field(None, max_length=500)
    # Whether the user wants this spot to be visible on the public map
    is_public: bool = True

    @field_validator("spot_name")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip()


class AdoptSpotOut(BaseModel):
    """A single adopted spot — returned from Firestore."""
    spot_id: str
    user_id: str
    coordinates: Coordinates
    spot_name: str
    ward_name: str
    species_common_name: str
    species_scientific_name: str | None
    notes: str | None
    status: AdoptionStatus
    is_public: bool
    green_points_earned: int = 0
    verification_count: int = 0
    adopted_at: datetime
    last_updated: datetime

    class Config:
        use_enum_values = True


class AdoptSpotUpdate(BaseModel):
    """Payload for PATCH /ledger/{spot_id} — all fields optional."""
    spot_name: str | None = None
    notes: str | None = None
    status: AdoptionStatus | None = None
    is_public: bool | None = None


# ── Verification Pipeline ──────────────────────────────────────────────────────

class VerificationStatus(str, Enum):
    APPROVED = "approved"    # Vertex AI detected a healthy sapling
    REJECTED = "rejected"    # No valid sapling detected
    PENDING = "pending"      # Queued for async processing


class VerificationResult(BaseModel):
    """
    Result of sending an image to Vertex AI for sapling detection.
    """
    spot_id: str
    verification_id: str
    status: VerificationStatus
    confidence_score: float = Field(..., ge=0, le=1)
    # Vertex AI model output labels
    detected_labels: list[str] = []
    # Points awarded (0 if rejected)
    green_points_awarded: int = 0
    # Community aggregation details
    community_matched_count: int = 0
    community_matched_ids: list[str] = []
    # one of: updated | no_match | skipped_not_approved | failed
    community_update_status: str | None = None
    message: str
    verified_at: datetime = Field(default_factory=datetime.utcnow)
    # GCS URI of the uploaded image
    image_gcs_uri: str | None = None


# ── User Profile ───────────────────────────────────────────────────────────────

class UserProfileOut(BaseModel):
    """Public-facing user profile with Green Ledger stats."""
    user_id: str
    display_name: str | None
    email: str | None
    total_green_points: int = 0
    total_trees_adopted: int = 0
    total_trees_verified: int = 0
    # City-wide rank (computed periodically by a Cloud Function)
    city_rank: int | None = None
    joined_at: datetime
    # Badge system — earned milestones
    badges: list[str] = []


# ══════════════════════════════════════════════════════════════════════════════
# FEATURE 1 — Pacha Vision: AR Metadata
# ══════════════════════════════════════════════════════════════════════════════

class ARModelScale(BaseModel):
    """
    Real-world scale hints for placing a 3D tree model in AR space.
    The frontend multiplies these by a scene unit factor.
    """
    x: float = Field(..., gt=0, description="Width scale (metres)")
    y: float = Field(..., gt=0, description="Height scale (metres)")
    z: float = Field(..., gt=0, description="Depth scale (metres)")


class ARModelMetadata(BaseModel):
    """
    Full AR asset descriptor returned by GET /assets/ar-model/{species_id}.
    Consumed by the Flutter ARCore / SceneView widget.
    """
    species_id: str = Field(..., examples=["azadirachta_indica"])
    common_name: str = Field(..., examples=["Neem"])
    scientific_name: str = Field(..., examples=["Azadirachta indica"])
    kannada_name: str | None = Field(None, examples=["ಬೇವು"])

    # ── 3D asset references ──────────────────────────────────────────────────
    # glTF 2.0 is the preferred format for ARCore/SceneView
    gltf_url: str = Field(..., description="Public GCS URL of the .glb (binary glTF) model")
    thumbnail_url: str = Field(..., description="Preview image for the species card")

    # ── AR placement parameters ──────────────────────────────────────────────
    real_world_scale_m: ARModelScale = Field(
        ..., description="Bounding box in metres at adult size"
    )
    # Sapling scale is shown immediately on adoption; adult after 5 years
    sapling_scale_factor: float = Field(
        default=0.15,
        description="Multiply adult scale by this to render a sapling",
    )
    # Y-axis offset so the trunk base sits on the AR ground plane
    ground_offset_m: float = Field(default=0.0, ge=0)

    # ── Environmental overlay data (shown as AR info cards) ──────────────────
    co2_absorption_kg_per_year: float
    expected_canopy_spread_m: float
    water_requirement: str
    growth_rate: str

    # ── Provenance ───────────────────────────────────────────────────────────
    model_version: str = "1.0"
    last_updated: datetime = Field(default_factory=datetime.utcnow)


# ══════════════════════════════════════════════════════════════════════════════
# FEATURE 2 — Green Corridor Clustering
# ══════════════════════════════════════════════════════════════════════════════

class CorridorStatus(str, Enum):
    ACTIVE = "active"           # 5+ verified trees within 100m radius
    EMERGING = "emerging"       # 3–4 verified trees — almost there
    INACTIVE = "inactive"       # Fewer than 3 verified trees


class GreenCorridor(BaseModel):
    """
    A geospatial cluster of verified planted trees constituting
    an Active Green Corridor in a BBMP ward.
    """
    corridor_id: str
    ward_name: str
    ward_id: str
    centre_coordinates: Coordinates
    radius_m: float = 100.0
    verified_tree_count: int
    status: CorridorStatus
    # User IDs of all contributors within this corridor
    contributor_user_ids: list[str] = []
    # Badge awarded to contributors of active corridors
    badge_awarded: str | None = None
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    last_audited: datetime = Field(default_factory=datetime.utcnow)


class CorridorAuditResult(BaseModel):
    """Result returned by POST /corridors/audit"""
    wards_audited: int
    new_corridors_detected: int
    badges_awarded: int
    corridors: list[GreenCorridor]
    audit_duration_seconds: float


class CommunityGoalType(str, Enum):
    TREE_COUNT = "tree_count"


class CommunityGeofence(BaseModel):
    center: Coordinates
    radius_km: float = Field(..., gt=0)


class CommunityProgressOut(BaseModel):
    community_id: str
    ward_name: str | None = None
    goal_type: CommunityGoalType
    target_value: int = Field(..., ge=1)
    current_value: int = Field(default=0, ge=0)
    members_count: int = Field(default=0, ge=0)
    geofence: CommunityGeofence
    progress_percent: float = Field(..., ge=0, le=100)
    target_reached: bool = False
    last_updated: datetime | None = None


class CommunityLeaderboardEntry(BaseModel):
    rank: int = Field(..., ge=1)
    community_id: str
    ward_name: str | None = None
    current_value: int = Field(default=0, ge=0)
    target_value: int = Field(..., ge=1)
    progress_percent: float = Field(..., ge=0, le=100)
    members_count: int = Field(default=0, ge=0)


# ══════════════════════════════════════════════════════════════════════════════
# FEATURE 3 — AI Carbon Credit & Tax Simulator
# ══════════════════════════════════════════════════════════════════════════════

class CarbonCreditRequest(BaseModel):
    """
    Input for POST /carbon/simulate.
    Can be called with a known species or raw coordinates
    (in which case we use the recommended species' CO2 data).
    """
    species_common_name: str = Field(..., examples=["Neem"])
    species_scientific_name: str | None = Field(
        None, examples=["Azadirachta indica"]
    )
    tree_age_years: float = Field(
        ..., gt=0, le=200,
        description="Age of the tree / expected age at evaluation",
        examples=[5.0],
    )
    num_trees: int = Field(
        default=1, ge=1, le=10000,
        description="Number of trees of this species to simulate",
    )
    # Optional: property value for rebate calculation
    property_value_inr: float | None = Field(
        None, gt=0,
        description="Current property valuation in INR for tax rebate simulation",
        examples=[5000000.0],
    )


class AnnualCarbonProfile(BaseModel):
    """Gemini-computed carbon sequestration breakdown for one year."""
    year: int
    co2_kg_sequestered: float
    cumulative_co2_kg: float
    # Equivalent in common units for public communication
    equivalent_car_km_offset: float = Field(
        ..., description="km a car would travel emitting this much CO2"
    )
    equivalent_flights_offset: float = Field(
        ..., description="Short-haul flights (~1000km) this offsets"
    )


class TaxRebateSimulation(BaseModel):
    """
    Simulated BBMP property tax rebate based on CO2 sequestration.
    Rule: 1% rebate for every 20 kg CO2 sequestered per year, capped at 20%.
    """
    annual_co2_kg: float
    rebate_percent: float = Field(..., ge=0, le=20)
    rebate_amount_inr: float | None = None  # None if property_value not supplied
    # Explanation for citizens
    rebate_calculation_note: str


class CarbonCreditResponse(BaseModel):
    """Full simulation result for POST /carbon/simulate"""
    species_common_name: str
    species_scientific_name: str | None
    num_trees: int
    tree_age_years: float

    # ── Carbon sequestration ─────────────────────────────────────────────────
    annual_co2_kg_per_tree: float
    total_annual_co2_kg: float
    cumulative_co2_kg_lifetime: float   # Integrated over tree_age_years

    # Year-by-year profile (first 10 years or up to tree_age, whichever shorter)
    annual_profile: list[AnnualCarbonProfile] = []

    # ── Carbon credit market value ───────────────────────────────────────────
    # Using India's voluntary carbon market rate (~₹800–1200 per tonne CO2)
    carbon_credit_value_inr: float
    carbon_credit_rate_inr_per_tonne: float = 1000.0

    # ── Tax rebate ───────────────────────────────────────────────────────────
    tax_rebate: TaxRebateSimulation

    # ── Gemini narrative ─────────────────────────────────────────────────────
    gemini_narrative: str = Field(
        ...,
        description="Plain-language Gemini explanation of the environmental ROI",
    )
    gemini_model_used: str
    disclaimer: str = (
        "Carbon estimates are AI-generated approximations. "
        "Tax rebates are illustrative simulations — not official BBMP policy. "
        "Consult a certified carbon auditor for compliance purposes."
    )


# ══════════════════════════════════════════════════════════════════════════════
# FEATURE 4 — Bhasha: Vernacular AI Voice Interface
# ══════════════════════════════════════════════════════════════════════════════

class SupportedLanguage(str, Enum):
    """Languages supported by the Bhasha voice interface."""
    KANNADA = "kn"         # Primary — Bengaluru's official language
    HINDI = "hi"
    TAMIL = "ta"
    TELUGU = "te"
    ENGLISH = "en"


class TranscriptionResult(BaseModel):
    """Output from Google Cloud Speech-to-Text."""
    transcript_english: str = Field(
        ..., description="Transcript converted to English for Gemini"
    )
    transcript_original: str = Field(
        ..., description="Transcript in the source language"
    )
    source_language: SupportedLanguage
    confidence: float = Field(..., ge=0, le=1)
    # BCP-47 language code used by Speech-to-Text
    detected_language_code: str


class VoicePrescriptionResponse(BaseModel):
    """
    Full response for POST /voice/prescribe.
    Contains the prescription PLUS Kannada (or source-language) translations
    of every human-readable field so the frontend can drive TTS.
    """
    # ── What the user said ───────────────────────────────────────────────────
    transcription: TranscriptionResult

    # ── English prescription (same shape as /prescribe) ─────────────────────
    prescription: PrescriptionResponse

    # ── Vernacular translation of the prescription ───────────────────────────
    # Key fields translated back for voice readback
    primary_species_name_vernacular: str = Field(
        ...,
        description="Common name in the user's language (e.g. Kannada: ಬೇವು)",
    )
    why_recommended_vernacular: str = Field(
        ...,
        description="why_recommended translated back to source language",
    )
    full_prescription_vernacular: str = Field(
        ...,
        description="Complete prescription summary in the source language, "
                    "ready for Text-to-Speech playback",
    )

    # ── Audio response (optional — set if TTS is enabled) ───────────────────
    # Base64-encoded MP3 bytes of the vernacular prescription readback
    audio_response_base64: str | None = None
    audio_content_type: str = "audio/mp3"

    # ── Metadata ─────────────────────────────────────────────────────────────
    source_language: SupportedLanguage
    processing_steps: list[str] = Field(
        default_factory=list,
        description="Ordered list of pipeline steps for debugging / transparency",
    )
